<MyWidget@BoxLayout>:
#<MyWidget>:
    label_widget: label_widget
    Button:
        text: 'Add Button'
        on_press: root.add_widget(label_widget)
    Button:
        text: 'Remove Button'
        on_press: root.remove_widget(label_widget)
    Button:
        text: 'Change Text'
        on_press: root.label_widget.text ="test"
    Label:
        id: label_widget
        text: 'widget'