<myrootwidget>:
    RelativeLayout

        size: 300,300
        Button:
            size_hint: 0.2,0.2
            pos_hint: {'center_x':0.7,'center_y':0.5}
            #pos_hint: {'center_x':0.7,'center_y':0.7}
            text: "pos_hint"
        Button:
            size_hint: 0.5, 0.2
            
            text:"size_hint"
        Button:
            size_hint: 0.2, 0.2
            pos:200,200
            text:"pos"

            